Made endpoints for user login and registration
ntu-khpi-reco-lab/movie-recommender pull request #10
Opened 2024-10-28 19:22 UTC by grdxbtw

2024-10-28 22:14 UTC, stanstork requested changes

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/config/RequestLoggingFilter.java
> +public class RequestLoggingFilter implements Filter {
extract this into `common` module (also update it in `location service`)

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/config/SecurityConfig.java
> +                        .anyRequest().authenticated());
add ` .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)`
it configures the app to avoid session creation for each request

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/config/SecurityConfig.java
> +        AuthenticationManagerBuilder authenticationManagerBuilder =
`AuthenticationManager` configuration can be simplified by injecting `AuthenticationConfiguration` and retrieving the `AuthenticationManager` from it

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/dto/UserDTO.java
> +public class UserDTO {
there should be two DTO classes
`UserCreateDTO` specifically for creating a user
`UserDTO` for responses
also additional fields required for user, such as `email, firstName, lastName`

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/dto/UserDTO.java
> +    public UserDTO(String username, String password) {
add `@Data, @AllArgsConstructor, and @NoArgsConstructor` annotations
these annotations will automatically generate all necessary getters, setters, and constructors

additionally, these annotations are already used in `location service`, so using them here will help maintain a uniform style across the project

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/dto/UserMapper.java
> +    public User toEntity(UserDTO userDTO) {
move the mapping methods into the `User` entity and DTOs classes themselves
(use `location service` as example)

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/entity/User.java
> +public class User {
add `@Data, @AllArgsConstructor, and @NoArgsConstructor` annotations

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    public UserDTO registerUser(UserDTO userDTO) {
use `UserCreateDTO` in parameters

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    public UserDTO registerUser(UserDTO userDTO) {
rename to `createUser`

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    // Регистрация нового пользователя через DTO
remove this comment

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    @Autowired
use constructor injection

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    // Поиск пользователя по имени пользователя
remove this comment

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
you also need a method to return full UserDTO

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/resources/db/migrations/V1__Create_user_table.sql
> +    location_id BIGINT UNIQUE NOT NULL
location is managed by `location service`, so it's not needed here

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/controller/UserController.java
> +    @Autowired
use constructor injection

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/controller/UserController.java
> +    // Регистрация пользователя через DTO
remove this comment

2024-10-28 22:14 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/controller/UserController.java
> +        try {
add a global exception handler, similar to the one in `location service`
there may be shared logic between the exception handlers, so consider moving this logic to a `common` module to maintain consistency and reusability across the project

2024-10-29 17:52 UTC, stanstork requested changes

2024-10-29 17:52 UTC, stanstork commented on user-service/src/main/resources/db/migrations/V1__Create_user_table.sql
> +    username DOUBLE PRECISION NOT NULL,
why `username` and `password` columns have a double type

2024-11-03 20:12 UTC, grdxbtw commented on user-service/src/main/java/com/movie/recommender/user/config/RequestLoggingFilter.java
> +public class RequestLoggingFilter implements Filter {
will do this in other pr 'Code review' for location service and user service

2024-11-04 19:37 UTC, stanstork requested changes

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/config/JwtUtil.java
> +        return Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token).getBody().getSubject();
extract `Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token)` to a separate method, such as `getClaims(String token)` (for example), to improve readability and reuse across methods
and add exception handling to this method with logging for any JWT parsing errors

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/config/JwtUtil.java
> +package com.movie.recommender.user.config;
move to package `com.movie.recommender.user.security`

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/controller/UserController.java
> +        UserDTO userDTO = userService.registerUser(userCreateDTO);
use `ResponseEntity.status(HttpStatus.CREATED).body(userDTO)` to set the correct 201 Created status code when returning the response for resource creation

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/dto/UserCreateDTO.java
> +    private String username;
add validation annotations to the fields to ensure required data is present

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/model/dto/UserCreateDTO.java
> +        User user = new User();
use constructor instead of setting each field individually to keep consistency

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +            throw new IllegalArgumentException("Username already exists");
instead of `IllegalArgumentException`, create a custom exception, for example `UsernameAlreadyExistsException`

2024-11-04 19:37 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/service/UserService.java
> +
remove any unnecessary empty lines and unused imports from the code

2024-11-04 19:39 UTC, stanstork requested changes

2024-11-04 19:39 UTC, stanstork commented on user-service/src/main/java/com/movie/recommender/user/controller/UserController.java
> +@RequestMapping("/api/users")
add versioning to the API (`/api/v1/...`)

2024-11-04 22:44 UTC, stanstork approved these changes

2024-11-04 22:44 UTC, merged